name = "DistanceMatrix"
uuid = "7b1335a8-b4b4-40d1-8a39-12a4d9b1302a"
authors = ["Alessandro Floris <floris.alessandro99@gmail.com>"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
